### ISSUE TITLE
安装后无法访问Docker

### ISSUE THREAD

**Issue by cnstampbird** [yonggekkk/CFwarp-yg#1]
is:issue is:open 安装后Docker无法访问，请问一下有没有修复的方案。

**Comment by yonggekkk** [comment]
安装过程中会有提示！双方冲突！只能选其一

**Comment by cnstampbird** [comment]
卸载后可以恢复Docker吗？不行的话又得重新部署了。如果可以把这个项目放到Docker容器就好了。

**Comment by yonggekkk** [comment]
卸载可以恢复

**Comment by cnstampbird** [comment]
> 卸载可以恢复

我试试，感谢大佬。

**Comment by alomerry** [comment]
现在也会和 docker 冲突吗

**Comment by yonggekkk** [comment]
> 现在也会和 docker 冲突吗

方案一当然冲突
