### ISSUE TITLE
总是“Socks5 WARP状态：未安装Socks5-WARP客户端”

### ISSUE THREAD

**Issue by zhychen1173** [yonggekkk/CFwarp-yg#2]
系统是 centos7。
安装脚本后，选 2 安装socks5-warp，多次尝试，结果都是“Socks5 WARP状态：未安装Socks5-WARP客户端”

请教该如何解决？谢谢。

**Comment by yonggekkk** [comment]
什么vps？有报错信息吗

**Comment by yonggekkk** [comment]
对了！centos7不支持安装socks5 warp
