### ISSUE TITLE
什么vps？有报错信息吗

### ISSUE THREAD

**Issue by zhychen1173** [yonggekkk/CFwarp-yg#3]
什么vps？有报错信息吗

_Originally posted by @yonggekkk in https://github.com/yonggekkk/CFwarp-yg/issues/2#issuecomment-1464936905_
 

搬瓦工，没看到报错信息。1里面开ipv4 v6都正常获得了ip，就是2 socks5提示未安装客户端。

**Comment by yonggekkk** [comment]
对了！centos7不支持安装socks5 warp
